#Profile flag
spring.profiles.active=local

# For testing using an in-memory H2 database (named testdb)
# Change details later for production database

# Uncomment for H2 database to be in-memory
spring.datasource.url=jdbc:h2:mem:testdb

# Uncomment for H2 database to persist
# spring.datasource.url=jdbc:h2:file:./data/testdb

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true

# Show formatted SQL with parameters
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Show parameter binding (this shows the actual values)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Enable H2 Console (add these lines)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Redis details
spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

# OAuth2 Configuration
# Resource server only needs to know how to validate JWTs
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${COGNITO_TOKEN_SIGNING_KEY_URL}

# Debug logging
logging.level.org.springframework.security=DEBUG

# Server configuration
server.port=8080