#Profile flag
spring.profiles.active=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME}

# Auto-generate tables and updates schema automatically:
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true

# Show formatted SQL with parameters
# spring.jpa.properties.hibernate.show_sql=true # Does the same thing as spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=${DB_HIBERNATE_DIALECT}


# Show parameter binding (this shows the actual values)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


#Redis details
spring.data.redis.host=${REDIS_URL}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=${REDIS_USERNAME}
spring.data.redis.password=${REDIS_PASSWORD}

# OAuth2 Configuration
# Resource server only needs to know how to validate JWTs
spring.security.oauth2.resourceserver.jwt.issuer-uri=${COGNITO_ISSUER}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${COGNITO_TOKEN_SIGNING_KEY_URL}

# Debug logging
logging.level.org.springframework.security=DEBUG

# Server configuration
server.port=8080